Deploy to second cloudfront bucket

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -265,6 +265,13 @@ jobs:
               --output text \
           )" >> $GITHUB_OUTPUT
 
+          echo "cloudfront-distribution-v2-id=$( \
+            aws cloudformation describe-stacks \
+              --stack-name ${{ needs.backend.outputs.stack-name }} \
+              --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionV2Id`].OutputValue' \
+              --output text \
+          )" >> $GITHUB_OUTPUT
+
       - name: clear frontend for ${{ env.RC_ENV }}
         run: |
           aws s3 rm --recursive ${{ steps.get-values.outputs.frontend-bucket-name }}
@@ -281,26 +288,21 @@ jobs:
       - name: clear frontend v2 for ${{ env.RC_ENV }}
         if: ${{ steps.retrieve-v2.outputs.has-v2 == 'true' }}
         run: |
-          aws s3 rm --recursive ${{ steps.get-values.outputs.frontend-bucket-v2-name }}/v2
-          echo "[INFO] S3 Bucket prefix for application component (FRONTEND V2) successfully cleared for ${RC_ENV^^}"
+          aws s3 rm --recursive ${{ steps.get-values.outputs.frontend-bucket-v2-name }}
+          echo "[INFO] S3 Bucket for application component (FRONTEND V2) successfully cleared for ${RC_ENV^^}"
 
       - name: deploy frontend v2 for ${{ env.RC_ENV }}
         if: ${{ steps.retrieve-v2.outputs.has-v2 == 'true' }}
         env:
           VERSION: ${{ needs.validation.outputs.VERSION }}
         run: |
-          aws s3 cp --recursive dist-v2/ ${{ steps.get-values.outputs.frontend-bucket-v2-name }}/v2/
+          aws s3 cp --recursive dist-v2/ ${{ steps.get-values.outputs.frontend-bucket-v2-name }}/
           echo "[INFO] Application component (FRONTEND V2) with version ${VERSION} successfully deployed for ${RC_ENV^^}"
 
       - name: invalidate cloudfront cache for ${{ env.RC_ENV }}
         run: |
           echo "[INFO] Executing invalidation against CloudFront Distribution Id ${{ steps.get-values.outputs.cloudfront-distribution-id }}"
-          invalidation_paths='/*'
-          if [[ "${{ steps.retrieve-v2.outputs.has-v2 }}" == 'true' ]]; then
-            invalidation_paths='/* /v2 /v2/*'
-          fi
-
-          invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-id }} --paths $invalidation_paths --output json \
+          invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-id }} --paths '/*' --output json \
             | jq -r '.Invalidation.Id')
 
           echo "[INFO] Waiting for invalidation to complete..."
@@ -310,4 +312,25 @@ jobs:
             echo "[INFO] CloudFront cache for application in ${RC_ENV^^} was successfully invalidated"
           elif [ $? -eq 255 ]; then
             echo "[WARN] CloudFront cache for application in ${RC_ENV^^} could not be invalidated"
+          fi
+
+      - name: invalidate cloudfront v2 cache for ${{ env.RC_ENV }}
+        if: ${{ steps.retrieve-v2.outputs.has-v2 == 'true' }}
+        run: |
+          if [[ "${{ steps.get-values.outputs.cloudfront-distribution-v2-id }}" == "None" ]]; then
+            echo "[INFO] CloudFront V2 distribution output not found for ${RC_ENV^^}, skipping invalidation"
+            exit 0
+          fi
+
+          echo "[INFO] Executing invalidation against CloudFront V2 Distribution Id ${{ steps.get-values.outputs.cloudfront-distribution-v2-id }}"
+          invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-v2-id }} --paths '/*' --output json \
+            | jq -r '.Invalidation.Id')
+
+          echo "[INFO] Waiting for invalidation to complete..."
+          aws cloudfront wait invalidation-completed --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-v2-id }} --id $invalidation_id
+
+          if [ $? -eq 0 ]; then
+            echo "[INFO] CloudFront V2 cache for application in ${RC_ENV^^} was successfully invalidated"
+          elif [ $? -eq 255 ]; then
+            echo "[WARN] CloudFront V2 cache for application in ${RC_ENV^^} could not be invalidated"
           fi
